version: '3.5'
services:
  bothelp-workflow:
    container_name: ${APP_CONTAINER_NAME_WORKFLOW}
    build:
      context: ${APP_BUILD_CONTEXT_WORKFLOW}
    restart: always
    volumes:
      - ${APP_PATH_HOST}:/var/www/html/
      - ${APP_STORAGE_WORKFLOW_LOGS_PM2}:/root/.pm2/logs/
      - ${APP_STORAGE_WORKFLOW_LOGS_SUPERVISOR}:/var/log/supervisor
    depends_on:
      - bothelp-rabbitmq
      - bothelp-db
  bothelp-db:
    container_name: ${APP_CONTAINER_NAME_DB}
    build:
      context: ${APP_BUILD_CONTEXT_POSTGRES}
    shm_size: 2gb
    restart: always
    command: "postgres -c config_file=/var/lib/postgresql/config/postgresql.conf"
    ports:
      - ${APP_PORT_DB}:5432
    volumes:
      - ${APP_STORAGE_DB}:/var/lib/postgresql
      - ${APP_STORAGE_DB_DATA}:/var/lib/postgresql/data
      - ${APP_STORAGE_DB_LOG}:/var/log/postgresql
      - ${APP_STORAGE_DB_POSTGRES_CONFIG}:/var/lib/postgresql/config/postgresql.conf
      - ./storage/postgresql/sql/init.sh:/docker-entrypoint-initdb.d/0_init.sh
    environment:
      - POSTGRES_DB=${APP_DB_POSTGRES_DB}
      - POSTGRES_USER=${APP_DB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${APP_DB_POSTGRES_PASSWORD}
  bothelp-rabbitmq:
    container_name: ${APP_CONTAINER_NAME_RABBITMQ}
    image: ${APP_IMAGE_RABBITMQ}
    restart: always
    volumes:
      - ${APP_STORAGE_RABBITMQ_ETC}:/etc/rabbitmq/
      - ${APP_STORAGE_RABBITMQ_DATA}:/var/lib/rabbitmq/
      - ${APP_STORAGE_RABBITMQ_LOGS}:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: ${APP_ENV_RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${APP_ENV_RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${APP_ENV_RABBITMQ_DEFAULT_PASS}
    ports:
      - ${APP_PORT_RABBITMQ_1}:5672
      - ${APP_PORT_RABBITMQ_2}:15672
